development:
  adapter: postgresql
  database: dchapman_io_development
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

test: &test
  adapter: postgresql
  database: dchapman_io_test
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: dchapman_io_production
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

cucumber:
  <<: *test

